site_name: napari-points-io
site_description: Simple io for points layers
site_author: Martin Weigert

theme: readthedocs


repo_url: https://github.com/maweigert/napari-points-io

pages:
- Home: index.md
